version: '3.5'

services:
  pid-app:
    container_name: pid-app-server
    build: .
    ports:
      - "8081:8080"
    #Dependencies name base on other services in compose file
    depends_on:
      - pid-db
    networks:
      - pid-server
    environment:
      - spring.datasource.url=jdbc:postgresql://pid-db/${DATABASE_NAME}
      - spring.datasource.username=${DATABASE_USER}
      - spring.datasource.password=${DATABASE_PASSWORD}
      - spring.profiles.active=dev

  pid-db:
    image: postgres
    container_name: pid-app-db
    ports:
      - ${DATABASE_PORT}:5432
    networks:
      - pid-server
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

networks:
  pid-server:
    driver: bridge