version: '3.5'

services:
  pid-app:
    container_name: pid-app-server
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - pid-db
    networks:
      - pid-server
    environment:
      - spring.datasource.url=${DATABASE_HOST}/${DATABASE_NAME}
      - spring.datasource.username=${DATABASE_USER}
      - spring.datasource.password=${DATABASE_PASSWORD}
      - spring.jpa.properties.hibernate.dialect=${DATABASE_DIALECT}

  pid-db:
    image: postgres
    container_name: pid-app-db
    ports:
      - "5432:5432"
    networks:
      - pid-server
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./sql/create_data.sql:/docker-entrypoint-initdb.d/create_data.sql

networks:
  pid-server:
    driver: bridge